{
 "title": "Symantec Endpoint Protection Networking",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "manager",
    "label": "Manager",
    "query": "label_values(symc_sepm_collector_errors, manager)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Agents per Network",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "symc_sepm_agent_ip_network_config_total"
    }
   ]
  },
  {
   "title": "Number of Agents per DNS Server",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "symc_sepm_agent_dns_server_config_total"
    }
   ]
  },
  {
   "title": "Number of Agents per DHCP Server",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "symc_sepm_agent_dhcp_server_config_total"
    }
   ]
  },
  {
   "title": "Number of Agents per WINS Server",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "symc_sepm_agent_wins_server_config_total"
    }
   ]
  }
 ]
}