{
 "title": "Symantec Endpoint Protection Manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "manager",
    "label": "Manager",
    "query": "label_values(symc_sepm_collector_errors, manager)"
   }
  ]
 },
 "panels": [
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agents",
   "type": "singlestat",
   "description": "The total number of SEP Agents (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agents_total{manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Outdated Version",
   "type": "singlestat",
   "description": "The number of SEP Agents with an outdated version (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_version_total{version!~\"14.[2-9].*\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Outdated Definitions",
   "type": "singlestat",
   "description": "The number of SEP agents with outdated definitions.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_cids_defset_version_total{version=~\"(18|190[0-3]|1904[0-1]).*\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "singlestat",
   "description": "The number of offline SEP Agents (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "symc_sepm_agent_is_online_total{manager=\"$manager\", status=\"No\"}"
    }
   ]
  },
  {
   "title": "Collector Errors",
   "type": "singlestat",
   "description": "The number of SEP Manager collector errors, if any (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "symc_sepm_collector_errors{manager=\"$manager\"}"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "graph",
   "description": "The total number of SEP Agents (graph).",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "symc_sepm_agents_total{manager=\"$manager\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Infected in 24h",
   "type": "singlestat",
   "description": "The number of infections on SEP Agents detected in the last 24 hours (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(symc_sepm_agent_is_infected{manager=\"$manager\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Virus Detected in 24h",
   "type": "singlestat",
   "description": "The number of virus detections on SEP Agents detected in the last 24 hours (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(time() - (symc_sepm_agent_last_virus_time{manager=\"$manager\"} / 1000) < (86400 * 1))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "SONAR Threats in 24h",
   "type": "singlestat",
   "description": "The number of SONAR threats on SEP Agents detected in the last 24 hours (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(time() - (symc_sepm_agent_last_heuristic_threat_time{manager=\"$manager\"} / 1000) < (86400 * 1))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "VDI Enabled",
   "type": "singlestat",
   "description": "The number of VDI Enabled SEP Agents (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(symc_sepm_agent_is_vdi_client{manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Recently Deployed",
   "type": "singlestat",
   "description": "The number of SEP Agents with Last Deployment date older than 2 weeks.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(time() - (symc_sepm_agent_last_deployment_time{manager=\"$manager\"} / 1000) < (86400 * 14))"
    }
   ]
  },
  { "title": "Agents Requiring Cleanup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Last Scan  2 weeks old",
   "type": "singlestat",
   "description": "The number of SEP Agents with Last Scan date older than 2 weeks.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(time() - (symc_sepm_agent_last_scan_time{manager=\"$manager\"} / 1000) > (86400 * 14))"
    }
   ]
  },
  {
   "title": "Not Scanned",
   "type": "singlestat",
   "description": "The number of SEP Agents with Last Scan date missing.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count((symc_sepm_agent_last_scan_time{manager=\"$manager\"} / 1000) == 0)"
    }
   ]
  },
  {
   "title": "Duplicate",
   "type": "singlestat",
   "description": "The total number of duplicate SEP Agents (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "symc_sepm_duplicate_agents_total{manager=\"$manager\"}"
    }
   ]
  },
  {
   "title": "Reboot Required",
   "type": "singlestat",
   "description": "The total number of  SEP agents with Reboot Required Status totals (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "symc_sepm_agent_reboot_required_status_total{manager=\"$manager\"} > 0"
    }
   ]
  },
  { "title": "Impaired Agent Functionality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Early Launch Anti-Malware",
   "type": "singlestat",
   "description": "The number of SEP Agents with Early Launch Anti-Malware (ELAM) not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_elam_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "AV Engine",
   "type": "singlestat",
   "description": "The number of SEP Agents with AV Engine not not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_av_engine_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Auto-Protection",
   "type": "singlestat",
   "description": "The number of SEP Agents with Auto-Protection not  On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_auto_protection_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Firewall",
   "type": "singlestat",
   "description": "The number of SEP Agents with firewall not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_firewall_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Tamper Protection",
   "type": "singlestat",
   "description": "The number of SEP Agents with Tamper Protection not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_tamper_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Proactive Threat Protection",
   "type": "singlestat",
   "description": "The number of SEP Agents with Proactive Threat Protection (PTP) not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_ptp_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Memory Exploit Mitigation",
   "type": "singlestat",
   "description": "The number of SEP Agents with Memory Exploit Mitigation not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_pep_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "SONAR",
   "type": "singlestat",
   "description": "The number of SEP Agents with SONAR not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_sonar_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Network Intrusion Prevention",
   "type": "singlestat",
   "description": "The number of SEP Agents with SONAR not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_network_cids_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "IE Browser Protection",
   "type": "singlestat",
   "description": "The number of SEP Agents with IE Browser Protection not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_cids_browser_ie_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Firefox Browser Protection",
   "type": "singlestat",
   "description": "The number of SEP Agents with Firefox Browser Protection not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_cids_browser_firefox_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  },
  {
   "title": "Download Advisor",
   "type": "singlestat",
   "description": "The number of SEP Agents with Download Advisor not On and not Disabled by Policy  (counter).",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(symc_sepm_agent_download_advisor_status_total{status!~\"(On|Disabled by policy)\",manager=\"$manager\"})"
    }
   ]
  }
 ]
}